#!/bin/sh

##############################################################################
##                                                                          ##
##  GroovyLab Bootstrap for UN*X                                            ##
##                                                                          ##
##  Needs "groovy" (1.1) comand in your classpath                           ##
##                                                                          ##
##############################################################################

DIRNAME=`dirname "$0"`

groovyConsole -cp $DIRNAME/lib/jmatharray.jar:$DIRNAME/lib/jmathplot.jar:$DIRNAME/src
